### ISSUE TITLE
Add proper support for Percona mysql 8 installation

### ISSUE THREAD

**Issue by priyank-R** [mittwald/salt-percona-formula#26]
The formula works fine for percona-mysql 5.7, but when it comes to installing 8, I had to make some modifications to the formula as follows:

1. In repo.sls, I activated the version 8 repo:

```
{% if percona_settings.version|string|trim == '8' %}
enable_version8_repo:
  cmd.run:
     - name: "percona-release setup ps80"
{% endif %}
```

2. Also, in server.sls and client.sls, I removed the versionstring from the name for the packages, as below:

`server.sls`
```
percona_server:
  pkg.installed:
    - name: {{ percona_settings.server_pkg }}
    - require:
{% for r in repolist %}
      - pkgrepo: {{ r }}
{% endfor %}
```
client.sls:
```
percona_client:
  pkg.installed:
    - name: {{ percona_settings.client_pkg }}
```

This helped me install percona-mysql8 without any problems. 

I'm not a yum or salt pro, so what I did is possibly a quick fix to make things work. If someone could guide me on how could I better write the state file to accomodate the changes I mentioned above, I would be able to test it on my machine and later contribute on this formula  with the changes. 

Thanks again, this formula saved a lot of time.

PS: I referred the official docs to get some ideas https://www.percona.com/doc/percona-server/8.0/installation/yum_repo.html
